<?php

use Illuminate\Database\Seeder;

class CompetencesSkillTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('competences_skill')->truncate();
        $competences_skill = [
            ['competences_id'=>'1','skill' => 'angular'],
            ['competences_id'=>'1','skill' => 'ASP.Net'],
            ['competences_id'=>'1','skill' => 'BizTalk'],
            ['competences_id'=>'1','skill' => 'C #'],
            ['competences_id'=>'1','skill' => 'HTML'],
            ['competences_id'=>'1','skill' => 'jQuery'],
            ['competences_id'=>'1','skill' => 'knockout'],
            ['competences_id'=>'1','skill' => 'MVC'],
            ['competences_id'=>'1','skill' => 'MVVM'],
            ['competences_id'=>'1','skill' => 'Oracle'],
            ['competences_id'=>'1','skill' => 'SharePoint'],
            ['competences_id'=>'1','skill' => 'SQL'],
            ['competences_id'=>'1','skill' => 'test tech'],
            ['competences_id'=>'1','skill' => 'Typescript'],
            ['competences_id'=>'1','skill' => 'VB.Net'],
            ['competences_id'=>'1','skill' => 'VBA'],
            ['competences_id'=>'1','skill' => 'WCF'],
            ['competences_id'=>'1','skill' => 'WF'],
            ['competences_id'=>'1','skill' => 'WPF'],
            ['competences_id'=>'2','skill' => 'autosar'],
            ['competences_id'=>'2','skill' => 'C'],
            ['competences_id'=>'2','skill' => 'C ++'],
            ['competences_id'=>'2','skill' => 'Embedded'],
            ['competences_id'=>'2','skill' => 'firmware'],
            ['competences_id'=>'2','skill' => 'FPGA'],
            ['competences_id'=>'2','skill' => 'labview'],
            ['competences_id'=>'2','skill' => 'Matlab'],
            ['competences_id'=>'2','skill' => 'microcontrollers'],
            ['competences_id'=>'2','skill' => 'QT'],
            ['competences_id'=>'2','skill' => 'S7'],
            ['competences_id'=>'3','skill' => 'ajax'],
            ['competences_id'=>'3','skill' => 'Android'],
            ['competences_id'=>'3','skill' => 'Apache'],
            ['competences_id'=>'3','skill' => 'Cobol'],
            ['competences_id'=>'3','skill' => 'Delphi'],
            ['competences_id'=>'3','skill' => 'Django'],
            ['competences_id'=>'3','skill' => 'Drupal'],
            ['competences_id'=>'3','skill' => 'Eclipse'],
            ['competences_id'=>'3','skill' => 'Flash'],
            ['competences_id'=>'3','skill' => 'GlassFish'],
            ['competences_id'=>'3','skill' => 'Groovy'],
            ['competences_id'=>'3','skill' => 'Hibernate'],
            ['competences_id'=>'3','skill' => 'hubris'],
            ['competences_id'=>'3','skill' => 'J2EE'],
            ['competences_id'=>'3','skill' => 'Java'],
            ['competences_id'=>'3','skill' => 'JavaScript'],
            ['competences_id'=>'3','skill' => 'JBoss'],
            ['competences_id'=>'3','skill' => 'Jenkins'],
            ['competences_id'=>'3','skill' => 'Joomla'],
            ['competences_id'=>'3','skill' => 'JSF'],
            ['competences_id'=>'3','skill' => 'junit'],
            ['competences_id'=>'3','skill' => 'Magento'],
            ['competences_id'=>'3','skill' => 'Maven'],
            ['competences_id'=>'3','skill' => 'MySQL'],
            ['competences_id'=>'3','skill' => 'Netbeans'],
            ['competences_id'=>'3','skill' => 'NoSQL'],
            ['competences_id'=>'3','skill' => 'Oracle'],
            ['competences_id'=>'3','skill' => 'Perl'],
            ['competences_id'=>'3','skill' => 'PHP'],
            ['competences_id'=>'3','skill' => 'python'],
            ['competences_id'=>'3','skill' => 'Ruby on rails'],
            ['competences_id'=>'3','skill' => 'SQL'],
            ['competences_id'=>'3','skill' => 'SWING'],
            ['competences_id'=>'3','skill' => 'symfony'],
            ['competences_id'=>'3','skill' => 'Tomcat'],
            ['competences_id'=>'3','skill' => 'TYPO3'],
            ['competences_id'=>'3','skill' => 'Vaadin'],
            ['competences_id'=>'3','skill' => 'Websphere'],
            ['competences_id'=>'3','skill' => 'WordPress'],
            ['competences_id'=>'4','skill' => 'Active Directory'],
            ['competences_id'=>'4','skill' => 'Cisco'],
            ['competences_id'=>'4','skill' => 'Citrix'],
            ['competences_id'=>'4','skill' => 'Cognos'],
            ['competences_id'=>'4','skill' => 'Helpdesk'],
            ['competences_id'=>'4','skill' => 'Helpdesk'],
            ['competences_id'=>'4','skill' => 'HP'],
            ['competences_id'=>'4','skill' => 'Linux'],
            ['competences_id'=>'4','skill' => 'lotus'],
            ['competences_id'=>'4','skill' => 'Network'],
            ['competences_id'=>'4','skill' => 'NSI'],
            ['competences_id'=>'4','skill' => 'Oracle'],
            ['competences_id'=>'4','skill' => 'SAS'],
            ['competences_id'=>'4','skill' => 'SQL'],
            ['competences_id'=>'4','skill' => 'Unix'],
            ['competences_id'=>'4','skill' => 'VMWare'],
            ['competences_id'=>'4','skill' => 'Windows'],
            ['competences_id'=>'5','skill' => 'ABAP'],
            ['competences_id'=>'5','skill' => 'Admin'],
            ['competences_id'=>'5','skill' => 'BASE'],
            ['competences_id'=>'5','skill' => 'BI'],
            ['competences_id'=>'5','skill' => 'BW'],
            ['competences_id'=>'5','skill' => 'Change Management'],
            ['competences_id'=>'5','skill' => 'CO'],
            ['competences_id'=>'5','skill' => 'CRM'],
            ['competences_id'=>'5','skill' => 'FI'],
            ['competences_id'=>'5','skill' => 'HCM'],
            ['competences_id'=>'5','skill' => 'MR'],
            ['competences_id'=>'5','skill' => 'ISU'],
            ['competences_id'=>'5','skill' => 'MM'],
            ['competences_id'=>'5','skill' => 'NETWEAVER'],
            ['competences_id'=>'5','skill' => 'PM'],
            ['competences_id'=>'5','skill' => 'PP'],
            ['competences_id'=>'5','skill' => 'QM'],
            ['competences_id'=>'5','skill' => 'SD'],
            ['competences_id'=>'5','skill' => 'WM'],
            ['competences_id'=>'6','skill' => 'Automated Tester'],
            ['competences_id'=>'6','skill' => 'Embedded Tester'],
            ['competences_id'=>'6','skill' => 'Functional Tester'],
            ['competences_id'=>'6','skill' => 'ISTQB'],
            ['competences_id'=>'6','skill' => 'Performance Engineering'],
            ['competences_id'=>'6','skill' => 'Quality Engineer'],
            ['competences_id'=>'6','skill' => 'Safety test'],
            ['competences_id'=>'6','skill' => 'Selenium'],
            ['competences_id'=>'6','skill' => 'Test Analyst'],
            ['competences_id'=>'6','skill' => 'Test Manager'],
            ['competences_id'=>'6','skill' => 'tester'],
            ['competences_id'=>'6','skill' => 'Testing'],
            ['competences_id'=>'7','skill' => 'BI'],
            ['competences_id'=>'7','skill' => 'BI EE'],
            ['competences_id'=>'7','skill' => 'Cognos'],
            ['competences_id'=>'7','skill' => 'Crystal Reports'],
            ['competences_id'=>'7','skill' => 'Data Warehouse'],
            ['competences_id'=>'7','skill' => 'ETL'],
            ['competences_id'=>'7','skill' => 'MS Analysis Services'],
            ['competences_id'=>'7','skill' => 'MS BI'],
            ['competences_id'=>'7','skill' => 'Oracle BI'],
            ['competences_id'=>'7','skill' => 'Oracle WH Builder'],
            ['competences_id'=>'7','skill' => 'TM1'],
            ['competences_id'=>'8','skill' => 'Product Owner'],
            ['competences_id'=>'8','skill' => 'Project Manager'],
            ['competences_id'=>'8','skill' => 'SCRUM Master'],
        ];
        DB::table('competences_skill')->insert($competences_skill);
    }
}
