<?php
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF','default_country'=>'0'],
            ['name' => 'Åland Islands', 'code' => 'AX','default_country'=>'0'],
            ['name' => 'Albania', 'code' => 'AL','default_country'=>'0'],
            ['name' => 'Algeria', 'code' => 'DZ','default_country'=>'0'],
            ['name' => 'American Samoa', 'code' => 'AS','default_country'=>'0'],
            ['name' => 'Andorra', 'code' => 'AD','default_country'=>'0'],
            ['name' => 'Angola', 'code' => 'AO','default_country'=>'0'],
            ['name' => 'Anguilla', 'code' => 'AI','default_country'=>'0'],
            ['name' => 'Antarctica', 'code' => 'AQ','default_country'=>'0'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG','default_country'=>'0'],
            ['name' => 'Argentina', 'code' => 'AR','default_country'=>'0'],
            ['name' => 'Armenia', 'code' => 'AM','default_country'=>'0'],
            ['name' => 'Aruba', 'code' => 'AW','default_country'=>'0'],
            ['name' => 'Australia', 'code' => 'AU','default_country'=>'0'],
            ['name' => 'Austria', 'code' => 'AT','default_country'=>'1'],
            ['name' => 'Azerbaijan', 'code' => 'AZ','default_country'=>'0'],
            ['name' => 'Bahamas', 'code' => 'BS','default_country'=>'0'],
            ['name' => 'Bahrain', 'code' => 'BH','default_country'=>'0'],
            ['name' => 'Bangladesh', 'code' => 'BD','default_country'=>'0'],
            ['name' => 'Barbados', 'code' => 'BB','default_country'=>'0'],
            ['name' => 'Belarus', 'code' => 'BY','default_country'=>'0'],
            ['name' => 'Belgium', 'code' => 'BE','default_country'=>'0'],
            ['name' => 'Belize', 'code' => 'BZ','default_country'=>'0'],
            ['name' => 'Benin', 'code' => 'BJ','default_country'=>'0'],
            ['name' => 'Bermuda', 'code' => 'BM','default_country'=>'0'],
            ['name' => 'Bhutan', 'code' => 'BT','default_country'=>'0'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO','default_country'=>'0'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ','default_country'=>'0'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA','default_country'=>'0'],
            ['name' => 'Botswana', 'code' => 'BW','default_country'=>'0'],
            ['name' => 'Bouvet Island', 'code' => 'BV','default_country'=>'0'],
            ['name' => 'Brazil', 'code' => 'BR','default_country'=>'0'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO','default_country'=>'0'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN','default_country'=>'0'],
            ['name' => 'Bulgaria', 'code' => 'BG','default_country'=>'0'],
            ['name' => 'Burkina Faso', 'code' => 'BF','default_country'=>'0'],
            ['name' => 'Burundi', 'code' => 'BI','default_country'=>'0'],
            ['name' => 'Cambodia', 'code' => 'KH','default_country'=>'0'],
            ['name' => 'Cameroon', 'code' => 'CM','default_country'=>'0'],
            ['name' => 'Canada', 'code' => 'CA','default_country'=>'0'],
            ['name' => 'Cape Verde', 'code' => 'CV','default_country'=>'0'],
            ['name' => 'Cayman Islands', 'code' => 'KY','default_country'=>'0'],
            ['name' => 'Central African Republic', 'code' => 'CF','default_country'=>'0'],
            ['name' => 'Chad', 'code' => 'TD','default_country'=>'0'],
            ['name' => 'Chile', 'code' => 'CL','default_country'=>'0'],
            ['name' => 'China', 'code' => 'CN','default_country'=>'0'],
            ['name' => 'Christmas Island', 'code' => 'CX','default_country'=>'0'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC','default_country'=>'0'],
            ['name' => 'Colombia', 'code' => 'CO','default_country'=>'0'],
            ['name' => 'Comoros', 'code' => 'KM','default_country'=>'0'],
            ['name' => 'Congo', 'code' => 'CG','default_country'=>'0'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD','default_country'=>'0'],
            ['name' => 'Cook Islands', 'code' => 'CK','default_country'=>'0'],
            ['name' => 'Costa Rica', 'code' => 'CR','default_country'=>'0'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI','default_country'=>'0'],
            ['name' => 'Croatia', 'code' => 'HR','default_country'=>'0'],
            ['name' => 'Cuba', 'code' => 'CU','default_country'=>'0'],
            ['name' => 'Curaçao', 'code' => 'CW','default_country'=>'0'],
            ['name' => 'Cyprus', 'code' => 'CY','default_country'=>'0'],
            ['name' => 'Czech Republic', 'code' => 'CZ','default_country'=>'0'],
            ['name' => 'Denmark', 'code' => 'DK','default_country'=>'0'],
            ['name' => 'Djibouti', 'code' => 'DJ','default_country'=>'0'],
            ['name' => 'Dominica', 'code' => 'DM','default_country'=>'0'],
            ['name' => 'Dominican Republic', 'code' => 'DO','default_country'=>'0'],
            ['name' => 'Ecuador', 'code' => 'EC','default_country'=>'0'],
            ['name' => 'Egypt', 'code' => 'EG','default_country'=>'0'],
            ['name' => 'El Salvador', 'code' => 'SV','default_country'=>'0'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ','default_country'=>'0'],
            ['name' => 'Eritrea', 'code' => 'ER','default_country'=>'0'],
            ['name' => 'Estonia', 'code' => 'EE','default_country'=>'0'],
            ['name' => 'Ethiopia', 'code' => 'ET','default_country'=>'0'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK','default_country'=>'0'],
            ['name' => 'Faroe Islands', 'code' => 'FO','default_country'=>'0'],
            ['name' => 'Fiji', 'code' => 'FJ','default_country'=>'0'],
            ['name' => 'Finland', 'code' => 'FI','default_country'=>'0'],
            ['name' => 'France', 'code' => 'FR','default_country'=>'1'],
            ['name' => 'French Guiana', 'code' => 'GF','default_country'=>'0'],
            ['name' => 'French Polynesia', 'code' => 'PF','default_country'=>'0'],
            ['name' => 'French Southern Territories', 'code' => 'TF','default_country'=>'0'],
            ['name' => 'Gabon', 'code' => 'GA','default_country'=>'0'],
            ['name' => 'Gambia', 'code' => 'GM','default_country'=>'0'],
            ['name' => 'Georgia', 'code' => 'GE','default_country'=>'0'],
            ['name' => 'Germany', 'code' => 'DE','default_country'=>'1'],
            ['name' => 'Ghana', 'code' => 'GH','default_country'=>'0'],
            ['name' => 'Gibraltar', 'code' => 'GI','default_country'=>'0'],
            ['name' => 'Greece', 'code' => 'GR','default_country'=>'0'],
            ['name' => 'Greenland', 'code' => 'GL','default_country'=>'0'],
            ['name' => 'Grenada', 'code' => 'GD','default_country'=>'0'],
            ['name' => 'Guadeloupe', 'code' => 'GP','default_country'=>'0'],
            ['name' => 'Guam', 'code' => 'GU','default_country'=>'0'],
            ['name' => 'Guatemala', 'code' => 'GT','default_country'=>'0'],
            ['name' => 'Guernsey', 'code' => 'GG','default_country'=>'0'],
            ['name' => 'Guinea', 'code' => 'GN','default_country'=>'0'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW','default_country'=>'0'],
            ['name' => 'Guyana', 'code' => 'GY','default_country'=>'0'],
            ['name' => 'Haiti', 'code' => 'HT','default_country'=>'0'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM','default_country'=>'0'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA','default_country'=>'0'],
            ['name' => 'Honduras', 'code' => 'HN','default_country'=>'0'],
            ['name' => 'Hong Kong', 'code' => 'HK','default_country'=>'0'],
            ['name' => 'Hungary', 'code' => 'HU','default_country'=>'0'],
            ['name' => 'Iceland', 'code' => 'IS','default_country'=>'0'],
            ['name' => 'India', 'code' => 'IN','default_country'=>'0'],
            ['name' => 'Indonesia', 'code' => 'ID','default_country'=>'0'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR','default_country'=>'0'],
            ['name' => 'Iraq', 'code' => 'IQ','default_country'=>'0'],
            ['name' => 'Ireland', 'code' => 'IE','default_country'=>'0'],
            ['name' => 'Isle of Man', 'code' => 'IM','default_country'=>'0'],
            ['name' => 'Israel', 'code' => 'IL','default_country'=>'0'],
            ['name' => 'Italy', 'code' => 'IT','default_country'=>'0'],
            ['name' => 'Jamaica', 'code' => 'JM','default_country'=>'0'],
            ['name' => 'Japan', 'code' => 'JP','default_country'=>'0'],
            ['name' => 'Jersey', 'code' => 'JE','default_country'=>'0'],
            ['name' => 'Jordan', 'code' => 'JO','default_country'=>'0'],
            ['name' => 'Kazakhstan', 'code' => 'KZ','default_country'=>'0'],
            ['name' => 'Kenya', 'code' => 'KE','default_country'=>'0'],
            ['name' => 'Kiribati', 'code' => 'KI','default_country'=>'0'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP','default_country'=>'0'],
            ['name' => 'Korea, Republic of', 'code' => 'KR','default_country'=>'0'],
            ['name' => 'Kuwait', 'code' => 'KW','default_country'=>'0'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG','default_country'=>'0'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA','default_country'=>'0'],
            ['name' => 'Latvia', 'code' => 'LV','default_country'=>'0'],
            ['name' => 'Lebanon', 'code' => 'LB','default_country'=>'0'],
            ['name' => 'Lesotho', 'code' => 'LS','default_country'=>'0'],
            ['name' => 'Liberia', 'code' => 'LR','default_country'=>'0'],
            ['name' => 'Libya', 'code' => 'LY','default_country'=>'0'],
            ['name' => 'Liechtenstein', 'code' => 'LI','default_country'=>'0'],
            ['name' => 'Lithuania', 'code' => 'LT','default_country'=>'0'],
            ['name' => 'Luxembourg', 'code' => 'LU','default_country'=>'0'],
            ['name' => 'Macao', 'code' => 'MO','default_country'=>'0'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK','default_country'=>'0'],
            ['name' => 'Madagascar', 'code' => 'MG','default_country'=>'0'],
            ['name' => 'Malawi', 'code' => 'MW','default_country'=>'0'],
            ['name' => 'Malaysia', 'code' => 'MY','default_country'=>'0'],
            ['name' => 'Maldives', 'code' => 'MV','default_country'=>'0'],
            ['name' => 'Mali', 'code' => 'ML','default_country'=>'0'],
            ['name' => 'Malta', 'code' => 'MT','default_country'=>'0'],
            ['name' => 'Marshall Islands', 'code' => 'MH','default_country'=>'0'],
            ['name' => 'Martinique', 'code' => 'MQ','default_country'=>'0'],
            ['name' => 'Mauritania', 'code' => 'MR','default_country'=>'0'],
            ['name' => 'Mauritius', 'code' => 'MU','default_country'=>'0'],
            ['name' => 'Mayotte', 'code' => 'YT','default_country'=>'0'],
            ['name' => 'Mexico', 'code' => 'MX','default_country'=>'0'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM','default_country'=>'0'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD','default_country'=>'0'],
            ['name' => 'Monaco', 'code' => 'MC','default_country'=>'0'],
            ['name' => 'Mongolia', 'code' => 'MN','default_country'=>'0'],
            ['name' => 'Montenegro', 'code' => 'ME','default_country'=>'0'],
            ['name' => 'Montserrat', 'code' => 'MS','default_country'=>'0'],
            ['name' => 'Morocco', 'code' => 'MA','default_country'=>'0'],
            ['name' => 'Mozambique', 'code' => 'MZ','default_country'=>'0'],
            ['name' => 'Myanmar', 'code' => 'MM','default_country'=>'0'],
            ['name' => 'Namibia', 'code' => 'NA','default_country'=>'0'],
            ['name' => 'Nauru', 'code' => 'NR','default_country'=>'0'],
            ['name' => 'Nepal', 'code' => 'NP','default_country'=>'0'],
            ['name' => 'Netherlands', 'code' => 'NL','default_country'=>'1'],
            ['name' => 'New Caledonia', 'code' => 'NC','default_country'=>'0'],
            ['name' => 'New Zealand', 'code' => 'NZ','default_country'=>'0'],
            ['name' => 'Nicaragua', 'code' => 'NI','default_country'=>'0'],
            ['name' => 'Niger', 'code' => 'NE','default_country'=>'0'],
            ['name' => 'Nigeria', 'code' => 'NG','default_country'=>'0'],
            ['name' => 'Niue', 'code' => 'NU','default_country'=>'0'],
            ['name' => 'Norfolk Island', 'code' => 'NF','default_country'=>'0'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP','default_country'=>'0'],
            ['name' => 'Norway', 'code' => 'NO','default_country'=>'0'],
            ['name' => 'Oman', 'code' => 'OM','default_country'=>'0'],
            ['name' => 'Pakistan', 'code' => 'PK','default_country'=>'0'],
            ['name' => 'Palau', 'code' => 'PW','default_country'=>'0'],
            ['name' => 'Palestine, State of', 'code' => 'PS','default_country'=>'0'],
            ['name' => 'Panama', 'code' => 'PA','default_country'=>'0'],
            ['name' => 'Papua New Guinea', 'code' => 'PG','default_country'=>'0'],
            ['name' => 'Paraguay', 'code' => 'PY','default_country'=>'0'],
            ['name' => 'Peru', 'code' => 'PE','default_country'=>'0'],
            ['name' => 'Philippines', 'code' => 'PH','default_country'=>'0'],
            ['name' => 'Pitcairn', 'code' => 'PN','default_country'=>'0'],
            ['name' => 'Poland', 'code' => 'PL','default_country'=>'0'],
            ['name' => 'Portugal', 'code' => 'PT','default_country'=>'0'],
            ['name' => 'Puerto Rico', 'code' => 'PR','default_country'=>'0'],
            ['name' => 'Qatar', 'code' => 'QA','default_country'=>'0'],
            ['name' => 'Réunion', 'code' => 'RE','default_country'=>'0'],
            ['name' => 'Romania', 'code' => 'RO','default_country'=>'0'],
            ['name' => 'Russian Federation', 'code' => 'RU','default_country'=>'0'],
            ['name' => 'Rwanda', 'code' => 'RW','default_country'=>'0'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL','default_country'=>'0'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH','default_country'=>'0'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN','default_country'=>'0'],
            ['name' => 'Saint Lucia', 'code' => 'LC','default_country'=>'0'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF','default_country'=>'0'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM','default_country'=>'0'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC','default_country'=>'0'],
            ['name' => 'Samoa', 'code' => 'WS','default_country'=>'0'],
            ['name' => 'San Marino', 'code' => 'SM','default_country'=>'0'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST','default_country'=>'0'],
            ['name' => 'Saudi Arabia', 'code' => 'SA','default_country'=>'0'],
            ['name' => 'Senegal', 'code' => 'SN','default_country'=>'0'],
            ['name' => 'Serbia', 'code' => 'RS','default_country'=>'0'],
            ['name' => 'Seychelles', 'code' => 'SC','default_country'=>'0'],
            ['name' => 'Sierra Leone', 'code' => 'SL','default_country'=>'0'],
            ['name' => 'Singapore', 'code' => 'SG','default_country'=>'0'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX','default_country'=>'0'],
            ['name' => 'Slovakia', 'code' => 'SK','default_country'=>'0'],
            ['name' => 'Slovenia', 'code' => 'SI','default_country'=>'0'],
            ['name' => 'Solomon Islands', 'code' => 'SB','default_country'=>'0'],
            ['name' => 'Somalia', 'code' => 'SO','default_country'=>'0'],
            ['name' => 'South Africa', 'code' => 'ZA','default_country'=>'0'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS','default_country'=>'0'],
            ['name' => 'South Sudan', 'code' => 'SS','default_country'=>'0'],
            ['name' => 'Spain', 'code' => 'ES','default_country'=>'0'],
            ['name' => 'Sri Lanka', 'code' => 'LK','default_country'=>'0'],
            ['name' => 'Sudan', 'code' => 'SD','default_country'=>'0'],
            ['name' => 'Suriname', 'code' => 'SR','default_country'=>'0'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ','default_country'=>'0'],
            ['name' => 'Swaziland', 'code' => 'SZ','default_country'=>'0'],
            ['name' => 'Sweden', 'code' => 'SE','default_country'=>'0'],
            ['name' => 'Switzerland', 'code' => 'CH','default_country'=>'0'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY','default_country'=>'0'],
            ['name' => 'Taiwan', 'code' => 'TW','default_country'=>'0'],
            ['name' => 'Tajikistan', 'code' => 'TJ','default_country'=>'0'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ','default_country'=>'0'],
            ['name' => 'Thailand', 'code' => 'TH','default_country'=>'0'],
            ['name' => 'Timor-Leste', 'code' => 'TL','default_country'=>'0'],
            ['name' => 'Togo', 'code' => 'TG','default_country'=>'0'],
            ['name' => 'Tokelau', 'code' => 'TK','default_country'=>'0'],
            ['name' => 'Tonga', 'code' => 'TO','default_country'=>'0'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT','default_country'=>'0'],
            ['name' => 'Tunisia', 'code' => 'TN','default_country'=>'0'],
            ['name' => 'Turkey', 'code' => 'TR','default_country'=>'0'],
            ['name' => 'Turkmenistan', 'code' => 'TM','default_country'=>'0'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC','default_country'=>'0'],
            ['name' => 'Tuvalu', 'code' => 'TV','default_country'=>'0'],
            ['name' => 'Uganda', 'code' => 'UG','default_country'=>'0'],
            ['name' => 'Ukraine', 'code' => 'UA','default_country'=>'0'],
            ['name' => 'United Arab Emirates', 'code' => 'AE','default_country'=>'0'],
            ['name' => 'United Kingdom', 'code' => 'GB','default_country'=>'1'],
            ['name' => 'United States', 'code' => 'US','default_country'=>'0'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM','default_country'=>'0'],
            ['name' => 'Uruguay', 'code' => 'UY','default_country'=>'0'],
            ['name' => 'Uzbekistan', 'code' => 'UZ','default_country'=>'0'],
            ['name' => 'Vanuatu', 'code' => 'VU','default_country'=>'0'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE','default_country'=>'0'],
            ['name' => 'Viet Nam', 'code' => 'VN','default_country'=>'0'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG','default_country'=>'0'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI','default_country'=>'0'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF','default_country'=>'0'],
            ['name' => 'Western Sahara', 'code' => 'EH','default_country'=>'0'],
            ['name' => 'Yemen', 'code' => 'YE','default_country'=>'0'],
            ['name' => 'Zambia', 'code' => 'ZM','default_country'=>'0'],
            ['name' => 'Zimbabwe', 'code' => 'ZW','default_country'=>'0'],
        ];
        DB::table('countries')->insert($countries);
    }
}